### PR TITLE
Update docstring to numpydoc format

### PR DESCRIPTION
**Pull request by hematthi**

### CODE REVIEW

**Comment by hematthi** [comment]
Fix docstring to include DataDict

**Comment by shbhuk** [comment]
1. DataDict input not included 
2. Check indentation on GitHub
3. Update output parameters for fit_relation() to the generalized ones from mle_fit()

**Comment by shbhuk** [comment]
Thanks for the push. Should I accept this pull request, or would you like to add docstrings for the other functions in `mle_fit_nd.py` through this as well?

**Comment by hematthi** [comment]
It's up to you... I might add some more docstrings for `mle_fit_nd.py`

**Comment by shbhuk** [comment]
I'll hold off for now then.

**Pull request merged**
